version: '3'

volumes:
  usrvol:
  bldvol:
  cchvol:

services:

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace   # bind mount the host project directory
      - usrvol:/root    # persist the home directory (bash_history etc.)
      - bldvol:/build   # store build artifacts on a docker volume
      - cchvol:/ccache  # ccache docker volume
    environment:
      - CCACHE_DIR=/ccache
    # keep open (do not auto-close)
    tty: true
    # alternatively ("tty" not working in some cases):
    # command: sleep infinity
